### ISSUE TITLE
Error: Minified React error #185

### ISSUE THREAD

**Issue by Senlar** [overextended/ox_inventory#351] opened 2021-11-27 04:17 UTC
**Describe the bug**
When in the inventory and shift click dragging, the UI bugs out and I get an NUI error. This is not normal action, but its happened twice to me in the last few minutes because I've accidently shift click dragged while in the inventory. So while this is not "normal" behavior, it will occur and cause errors.

**To Reproduce**
1. Open Inventory
2. Hold SHIFT then LEFT CLICK on and item and drag it to the UPPER RIGHT corner of the screen beyond the inventory grid.
3. Blur sticks on your screen but the inventory disappears and produces the NUI error attached below.

**Expected behavior**
People shouldn't be able to accidently cause this error. Maybe there's some event that can be listened for and stopped to prevent it.

**Screenshots**
![image](https://user-images.githubusercontent.com/1503963/143667636-0f9c69b7-5af6-4de6-9eb6-11481ffe1bbb.png)

**Additional context**

**Comment by LukeWasTakenn** [comment] 2021-11-27 12:19
I can't reproduce this neither with a bult environment nor a development one.

**Comment by dunak-debug** [comment] 2021-11-27 12:43
`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

**Comment by LukeWasTakenn** [comment] 2021-12-10 10:02
This should now fully be resolved with bdc14374a26c604021ba8599a74b2d4ac45192a2.

**Closed by LukeWasTakenn** 2021-12-10 10:02 UTC
Labels: bug
