### ISSUE TITLE
Police Armory and other addons shop not openning

### ISSUE THREAD

**Issue by viper052186** [overextended/ox_inventory#677] opened 2022-04-21 06:05 UTC
police shop and other addons shop not opening in qtarget function when the server restart automatically by txadmin

also when your restart the server manually

but shops like liquor, shops, black market is openning well

**Comment by thelindat** [comment] 2022-04-21 06:19
Pretty sure that was already fixed; and you’re looking for qtarget, not ox inventory.

**Comment by viper052186** [comment] 2022-04-21 10:47
it is working fine with ox_inventory v2.8.1

qtarget, ox-lib. up to date. only i did is update the ox_inventory v2.8.2

**Comment by viper052186** [comment] 2022-04-21 11:04
![image](https://user-images.githubusercontent.com/70097175/164444976-7f303d69-d464-4b83-9db1-06a6c105a205.png)

**Comment by viper052186** [comment] 2022-04-21 11:25
This error shows when i change my job...for example from police i can access the police armory

then if i change my job to ambulance...the shop of ambulance will not work

even tho if you change it to mechanic, the shop for mechanic will not work.

**Comment by viper052186** [comment] 2022-04-21 12:14
here is the video, hope it would help

https://streamable.com/t0whuv

**Comment by thelindat** [comment] 2022-04-22 03:11
Cycling through jobs on ESX, no issue.

**Comment by varkosqc** [comment] 2022-04-22 14:02
I have the same issue.

**Comment by viper052186** [comment] 2022-04-22 22:42
once the player change his job, he/she cannot access addons shop anymore

**Comment by thelindat** [comment] 2022-04-25 08:19
> once the player change his job, he/she cannot access addons shop anymore

Yes, I understand what you're reporting - however, it does not occur on either of my test servers.

**Comment by lush0n3** [comment] 2022-05-02 07:48
> > once the player change his job, he/she cannot access addons shop anymore
> 
> Yes, I understand what you're reporting - however, it does not occur on either of my test servers.


Apparently there is an error with the stores that have the group written. Example:

this store works well:
`PoliceArmoury = {
		name = 'Armeria policial',
		groups = shared.police,`
		
but this doesn't work

`Medicine = {
		name = 'Botiquin',
		groups = {
			['ambulance'] = 0
		},`

_It happens with all the stores that have the name written..._
_It only happens when changing jobs, example (setjob or script)_
![image](https://user-images.githubusercontent.com/87586904/166201403-50fa1cec-e497-4e4c-b0ac-1aed5e1e239a.png)

**Comment by thelindat** [comment] 2022-05-02 07:53
shared.police is equal to `{ ['police'] = 0, ['sheriff'] = 0 }` by default, the exact same format as above. This is still _not a reproducible issue_.

What's with this stupid fucking yellow outline? I can read. I know what the line is, and there isn't a situation in which it should be _nil_; nor have I managed to get it to be _nil_.

**Comment by thelindat** [comment] 2022-05-02 08:01
Closing since nobody wants to give me information.

An error message doesn't count as information.

**Closed by thelindat** 2022-05-02 08:01 UTC
Labels: bug
