### ISSUE TITLE
Text UI for shops

### ISSUE THREAD

**Issue by Jozobro** [overextended/ox_inventory#752] opened 2022-06-29 10:10 UTC
**Inventory text ui for shops**

Hello, I would like to add the possibility to use the text ui from ox_lib because I think it would be one of the things that would be worth seeing in this inventory thank you <3

**Comment by thelindat** [comment] 2022-06-29 22:02
Duplicate of https://github.com/overextended/ox_inventory/issues/461

**Closed by thelindat** 2022-06-29 22:02 UTC
Labels: enhancement
