### ISSUE TITLE
Dumpster netId is not the same for everyone

### ISSUE THREAD

**Issue by Skryptific** [overextended/ox_inventory#345] opened 2021-11-22 22:11 UTC
**Describe the bug**
When opening a dumpster, the network id is not the same for everyone, thus seeing differences in the contents of the container.

**To Reproduce**
1. Open a dumpster yourself.
2. Let another player open the dumpster as well.

**Expected behavior**
Seeing the same contents in the same dumpster.

**Screenshots**
![image](https://user-images.githubusercontent.com/48567607/142942326-df485a0d-ea0b-422f-b731-fbb555109de3.png)
![image](https://user-images.githubusercontent.com/48567607/142942438-19eec513-a0bf-40e6-9070-c8e9b4de6b81.png)

**Additional context**
I am running the latest version of the main branch and OneSync Infinity.

**Comment by thelindat** [comment] 2021-11-24 07:57
NetID should always be synced and from my testing it should work fine, but god knows. Issue has been reported by some and not others.

Are you using any of the onesync convars for workarounds and migrations? Is this only when the dumpster is in or out of scope that the ID doesn't sync?

**Comment by dolutattoo** [comment] 2021-11-27 01:13
I reported the same issue with linden_inventory a couple weeks ago. To help to reproduce, open a dumpster without touching it, then close your inventory, kick the dumpster and re-open it. It works better if someone else is near you.

**Comment by dolutattoo** [comment] 2021-11-28 05:34
I could re-open an issue but it's almost the exact same issue I think:
https://streamable.com/t04fz6

**Comment by thelindat** [comment] 2021-11-29 20:34
2 weeks ago I removed some unnecessary code, such as checking if a value was false rather than `not value`; a typo was made for the dumpster check.

See if it's working with https://github.com/overextended/ox_inventory/commit/499089f836837c2b413805d617286151b1419ec7

**Closed** 2021-11-30 13:07 UTC
Labels: bug

**Comment by dolutattoo** [comment] 2021-11-30 18:04
> 

So I tested again with a friend:
- I go alone to a place where there is some dumpsters,
- I bring my friend to me using `/bring [id]`,
- My friend go to a dumpster, open it, and then kick it,
- Instantly, the dumpster is dupplicated, but the dupplicate is deleted around 1 sec later (That was not the case before your commit),
- Looks like the dumpster is dupplicated only for the player who watch someone else kicking it.

Video:
https://streamable.com/16s3z7

Is there any snippet that I can use in the dumpster target event to check any owner weird thing?
