### ISSUE TITLE
Inventory state reverted after re-opening

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#469] opened 2022-01-16 22:10 UTC
**Describe the bug**
Sometimes items are not updated when you re-open your inventory.
I'm not the only server owner who have this issue, and we needs more tests to get 100% sure reproduce steps.

Sometimes:
- When a player move an item, the slot is not updated when he re-open the inventory,

- When a player drag something from a right inventory, he's back on the previous place when re-opening, and sometimes the bug is here only when the item is moved in hotbar,

- For LSPD officers, who have flashlights (personal server context) containers items are sometimes only accessible by the hotbar shortcuts, and not by dragging on the USE button. To fix the bug, the player have to remove the flashlight item from his inventory. The container stay accessible only if the player stands on the flashlight drop, not if he move few metters away (into a blank drop)

**To Reproduce**
??

**Additional context**
I know other people have similar bugs from the ~= 10 latest commits. Please comment this issue so we can find how to reproduce.

**Comment by dolutattoo** [comment] 2022-01-17 00:37
> I'd need to know what commit of you're using in production.

Latest commits. Pretty sure its about updateInventory > updateSlot changes

**Comment by thelindat** [comment] 2022-01-17 02:31
That was just a change to an event name; shouldn’t be the merging of both update methods since I just merged the logic of swap slots and update inventory functions, too.

only actual code change is the item count tracking, but I don’t believe anything was changed with setting slots. Will look into it.

Is it when moving to empty slots, swapping, or what?

**Comment by dolutattoo** [comment] 2022-01-17 04:31
> Is it when moving to empty slots, swapping, or what?

I personnaly didnt had the chance to get the bug. But a loooot of my players have it, some of the staff too.
Looks like its when moving on empty slots, yeah. I know that some others people have same issue, so a lot of people should have this problem, could be great to have their feedbacks too :(

**Comment by antond15** [comment] 2022-01-17 06:54
It's caused by changes in https://github.com/overextended/ox_inventory/commit/28d388822a5d268afbad256a6ca7b8c796d8cb4e (and https://github.com/overextended/ox_inventory/commit/ce6ef277aa649867cbf68f2a6e5e83630dc073d9).
I reverted only these changes and it works well.

Later today, I will try to reproduce it with my team.

**Comment by antond15** [comment] 2022-01-17 16:19
After some testing, we found this:
- https://streamable.com/tvdauz
_Main screen - **P1**_
_Small screen - **P2**_

  This happened right after starting the inventory resource without previously opening the inventory (on both sides).
  After _P2_ took some items from _P1_, _P1_ still had them in the same slots, but couldn't interact with them.
  No client or server errors were seen.

- https://streamable.com/dtrzjp
This happened after few minutes from getting robbed. The slot from which the item was stolen (**6**) remained visually "empty" in UI, but was acting as normal (_swapping with other slots_).

Client clearly doesn't properly apply the changes sent from server.

**Comment by thelindat** [comment] 2022-01-18 17:27
ce6ef27 is simply a change to event name, and there's _nothing_ changed to the data being sent or set for the inventory slot in 28d3888; the only change is that item count is being tracked.

Right now I can't even figure out why the item tracking is so weird with slot 1, let alone this stuff with refreshslots.

**Comment by dolutattoo** [comment] 2022-01-18 17:55
Looks like last commit ([4a2b6ef](https://github.com/overextended/ox_inventory/commit/4a2b6ef585bb4e06a3427ef78b80f4e0329bdcd1)) fixed the first problem reported by @antond15. That I was currently reproducing while testing with another player.

**Comment by thelindat** [comment] 2022-01-19 06:54
Pending feedback from @antond15 before closing issue.

**Comment by antond15** [comment] 2022-01-19 15:44
> Pending feedback from @antond15 before closing issue.

Everything is fixed!

**Closed** 2022-01-19 20:47 UTC
