### ISSUE TITLE
Placeholders not utilised in some locales (i.e. 'Removed %sx')

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#407] opened 2021-12-27 01:45 UTC
**Is your feature request related to a problem? Please describe.**
When you delete an item using `/removeitem` for example, the notification doesnt display the count. And it can be weird from a player perspective, especially when you remove them some money.

**Describe the solution you'd like**
The remove item notification should display how many item was removed, like linden_inventory did.

**Screenshot**
![image](https://user-images.githubusercontent.com/47056777/147426056-0ff0235f-2e06-466a-820a-3dafa85ae0d7.png)

**Comment by thelindat** [comment] 2021-12-27 06:47
This was an issue caused by the change to item notifications (supporting metadata.label and metadata.image). Should be resolved with new commit.

**Comment by thelindat** [comment] 2021-12-27 18:38
French, Brazilian Portuguese, and Spanish are missing placeholders in some of their locales, possibly others too (haven't looked).

**Closed** 2022-01-01 07:33 UTC
Labels: help wanted
