### ISSUE TITLE
i get this error after the last update 

### ISSUE THREAD

**Issue by PhilipPlein** [overextended/ox_inventory#440] opened 2022-01-06 12:15 UTC
hi , i've download this resource like 7 days ago and everything work fine until the last update . now i get this error and the inventory crash the i have to restart the ox_inventory to working this is the error screenshot . if someone could help me to fix this I will be grateful[https://drive.google.com/file/d/19tMCKiqErlY3jdqnuu3IE4PCObMUQGcP/view?usp=sharing](url)

**Comment by thelindat** [comment] 2022-01-06 12:24
We need to know your actual steps and config to do anything here, because it's not something we've ever reproduced.

**Comment by PhilipPlein** [comment] 2022-01-06 14:13
Hello again, excuse my English. I am using the fork version of extended and I have followed all the steps to install everything correctly. and until a week ago everything was going well except that I had not realized the problem of the crash when I bought the gun license. I have attached a video link so you can see exactly what the problem is. link video proof [https://youtu.be/BOmZ2uwelXs](url) . I forgot to add that when buying the license everything is perfectly saved in the user_licences table. 
Any help would come in handy, thank you again

**Comment by LukeWasTakenn** [comment] 2022-01-06 15:51
Does it happen every time you try to purchase a license?

Also what locale is this?

**Comment by PhilipPlein** [comment] 2022-01-06 16:47
yes 

> Does it happen every time you try to purchase a license?
> 
> Also what locale is this?

yes its happens everytime i try to buy the weapon license . now im using ES local but it happen with EN local too . so when it happens as you can see on video the inventory get stacked so i have tu restart it to continue using it but the thing is after i restart the inventory is say there i have license weapon yet and everything work fine . on database i can see the new imput on user_license , i use a fork extended ox and also esx_license from fork addons ox .

**Comment by LukeWasTakenn** [comment] 2022-01-06 18:42
Resolved in latest commit

**Closed by LukeWasTakenn** 2022-01-06 18:42 UTC
Labels: bug
