### ISSUE TITLE
crafting system - quantity to craft is not working

### ISSUE THREAD

**Issue by fferrandini** [overextended/ox_inventory#1194] opened 2023-03-09 18:15 UTC
**Describe the bug**
i can't craft >1 items at same time, beside having available ingredients.

**To Reproduce**
if a item needs 2 of X and i have 4 X , i put "2" in quantity input, drag the item to be crafted, it crafts only one. 

**Expected behavior**
it should craft 2 items, remove 4 ingredients, plus it would be nice to multiply crafting time by quantity being crafted.
if 1 item takes 5 seconds, 2 would take 10 seconds and so on.

**Comment by thelindat** [comment] 2023-03-10 02:27
Duplicate of #1023

**Closed by thelindat** 2023-03-10 02:27 UTC
Labels: enhancement
