### ISSUE TITLE
Highlighting/dragging input amount causes CEF crash

### ISSUE THREAD

**Issue by NupNipz** [overextended/ox_inventory#1314] opened 2023-05-13 08:54 UTC
**Describe the bug**
Its really weird and it happens at the weirdest moment, and I'm not able to reproduce it consistently but i figured out that it always happens when changing the item count, so for example:

I change the item count to "5", but if I do this fast or make a typo and adapt it to 5, then the UI will randomly bug out and i will needs to reload my client to be able to get the NuiFocus of and the inventory closed.

**Framework**
I tried on either QB and ESX, both are having the same issue.

**Resource version**
currently using 2.29.2, but is not happening since this release, its going on for a little while now, and it`s not only happening on my server.

**To Reproduce**
As i said before, i cannot reproduce it consistently, but here is a clip of what's happening, happens in like the first 10 seconds of the clip.

https://medal.tv/games/gta-v/clips/195b5pjwXO4QZu/d1337c2Iy3VS?invite=cr-MSxxQXEsMTIzMzQxNzgs

**Expected behavior**
that the inventory changes the item count like it is supposed to, instead of freezing/bugging out

**Comment by LukeWasTakenn** [comment] 2023-10-13 13:23
This seems to be an issue with CEF itself that causes CEF to completely crash.

After several reproduction videos and steps pointed out by people I am completely unable to reproduce this, yet some people are able to reproduce it very consistently.

The issue occurs when trying to drag and wiggle the contents of the input, so not when the input value itself changes, which most certainly makes it an issue with CEF as the input handler for changes doesn't even run, and the input is just the native html input tag with type number (changing the type also doesn't seem to fix the issue).

**Comment by thelindat** [comment] 2023-10-14 02:41
https://forum.cfx.re/t/select-drag-drop-hang-cef-entirely/5057545

**Comment by LukeWasTakenn** [comment] 2023-10-28 16:10
Closing for now as it seems the workaround commit has resolved the issue.

**Closed by LukeWasTakenn** 2023-10-28 16:10 UTC
Labels: bug, help wanted, needs information
