### ISSUE TITLE
Feature: Inventory Hooks

### ISSUE THREAD

**Issue by Ehbw2** [overextended/ox_inventory#929] opened 2022-10-29 20:17 UTC
**Describe the solution you'd like**
For People who want to modify how ox_inventory behaves, for example preventing certain items from being stolen from a players inventory, unless there is already a configuration option, it would require modifying ox_inventory which can make updating the inventory a Tedious task sometimes (e.g. in cases where certain parts of the script is heavily changed). 

So instead of needing to modify the code in order to achieve what server-owners want. I purpose the idea of implementing "hooks" within the inventory to allow external resources to modify parts of how the inventory works without the need of modifying the inventories code directly, essentially how [cfx-default-chat](https://github.com/citizenfx/cfx-server-data/blob/0210252be7c17745fa30220e12c19e0d2f19af02/resources/%5Bgameplay%5D/chat/sv_chat.lua#L27) handles this, where a resource is able to register a function to be executed when a message is sent. How my suggestion breaks off from how hooks are used within base CFX Resources is instead of requiring a separate export for each hook added and - at least for the CFX example - only being able to read the data being sent. The hooking system should only use one export and require the script to clarify which hook it wants to listen for and for the setting data either passing a setter function similar to how ``populationPedCreating`` does or listening for the returned value from the hooks callback.

An quick and poorly written example

```lua
local ox_inventory = exports['ox_inventory']

ox_inventory:registerHook('SwapItems', function(itemName, fromInventory, toInventroy, setters --[[ Example ]] )
        -- Do some shit
        setters.setCanceled(true) 

       -- Or
       return {canceled = true}
end)
```
This example would hook to the 'SwapItems' hook which would trigger when an item is transferred between to inventory and cancel the transaction, which would act the same if the SwapItem invalid was invalid (e.g. container full etc.)

**Describe alternatives you've considered**
Aside from directly modifying ox_inventory code, No.

**Comment by thelindat** [comment] 2022-11-04 05:20
```lua
if not lib then return end

local eventHooks = {}

function TriggerEventHooks(event, ...)
    local hooks = eventHooks[event]

    if hooks then
        for i = 1, #hooks do
            local _, response = pcall(hooks[i], ...)

            if response == false then
                return false
            end
        end
    end

    return true
end

exports('registerHook', function(event, cb)
    if not eventHooks[event] then
        eventHooks[event] = {}
    end

    rawset(cb, 'resource', GetInvokingResource())
    eventHooks[event][#eventHooks[event] + 1] = cb
end)

AddEventHandler('onResourceStop', function(resource)
    for _, hooks in pairs(eventHooks) do
        for i = #hooks, 1, -1 do
            if hooks[i].resource == resource then
                table.remove(hooks, i)
            end
        end
    end
end)

exports.ox_inventory:registerHook('swapItems', function(payload)
    -- print(json.encode(payload, {indent=true}))
    -- return false

    Wait(1000)
end)

```

```lua
if not TriggerEventHooks('swapItems', {
    fromInventory = fromInventory.id,
    fromSlot = data.fromSlot,
    fromType = data.fromType,
    toInventory = toInventory.id,
    toSlot = data.toSlot,
    toType = data.toType,
    count = data.count,
}) then return end
```

This "works" as suggested, but there's some things to consider.
- What kind of data should be included in the payload?
- Filtering. If you have several resources using hooks, moving items will become more expensive and run into unexpected behaviour (i.e. blocking threads, errors).
  - Filter by item? By inventory?
  
Adding in api like this will open up more cases of user-error, which people will attribute to the inventory rather than 3rd party scripts, and I also need to be 100% on the implementation to ensure we don't have compatibility issues in the future.

**Comment by Ehbw2** [comment] 2022-11-04 17:19
> Filtering. If you have several resources using hooks, moving items will become more expensive and run into unexpected behaviour (i.e. blocking threads, errors).

What may make sense is to potentially provide an additional argument to the ``registerHook`` export allowing for optional configuration, for example. If you didn't want to cancel any actions with a hook, it could then be configured to run concurrently
to not block the thread.

What also may make sense is to have the inventory warn owners when a hook takes over X (an example being 100ms) amount of time to finish, as ideally within the hooks it wouldn't make an awful lot of sense to trigger MySQL Sync queries or heavy functions.

As for errors, all you really can do is catch them when the hook fails and complain to console and either allow the rest of the hooks to continue or end hook execution from that point for that action.

> Filter by item? By inventory?

What might not be a bad idea is to implement a system similar to how statebag listeners behave where you can listen to certain inventory, 


> Adding in api like this will open up more cases of user-error, which people will attribute to the inventory rather than 3rd party scripts

Yes, unfortunately server owners don't seem to be capable to think logically and will complain. Even if the error was pointing to the resource causing it people would likely ignore that fact and base their logic on the ``[script:ox_inventory]`` channel.

As for unintended behaviour with 3rd party hooks, it may not be a bad idea to include additional configuration to:
1) print a debug message every time a hook is triggered, this *may* be useful to determine which hook may be causing unintended behaviour.
2) to disable any hooks entirely, this would be useful at determining if a third party hook is causing intended behaviour.

**Comment by thelindat** [comment] 2022-11-04 22:01
```lua
local ox_inventory = exports.ox_inventory

ox_inventory:registerHook('swapItems', function(payload)
    print(json.encode(payload, {indent=true}))
    return false
end, {
    print = true,
    itemFilter = {
        water = true,
        burger = true,
    },
    matchInventory = '^glove'
})
```

Simple set for itemFilter, so only water and burger trigger this hook.
matchInventory uses string.match, so in this case we can prevent water and burger from being moved to or from a glovebox.

**Comment by thelindat** [comment] 2022-11-05 21:27
What I have currently, where else would you like hooks to be added?
I haven't done buyItem since I still intend to redo shops in the future, which would likely require breaking changes.

```lua
local ox_inventory = exports.ox_inventory

-- Blacklist "water" from being moved to/from gloveboxes and trunks.
ox_inventory:registerHook('swapItems', function(payload)
	print(json.encode(payload, { indent = true }))
end, {
	print = true,
	itemFilter = {
		water = true,
	},
	inventoryFilter = {
		'^glove[%w]+',
		'^trunk[%w]+',
	}
})

-- Prevent gloveboxes and trunks from being opened.
ox_inventory:registerHook('openInventory', function(payload)
	print(json.encode(payload, { indent = true }))
	return false
end, {
	print = true,
	inventoryFilter = {
		'^glove[%w]+',
		'^trunk[%w]+',
	}
})

-- Gives all newly-created "water" a new label.
ox_inventory:registerHook('createItem', function(payload)
	print(json.encode(payload, { indent = true }))
	local metadata = payload.metadata
	metadata.label = 'Mineral Water'
	return metadata
end, {
	print = true,
	itemFilter = {
		water = true,
	},
})
```

**Comment by Ehbw2** [comment] 2022-11-05 21:33
buyItem would of been my only suggestion. just one idea, with hooks that allow you to cancel it (e.g. openInventory, swapItems), do you think it would be worth to allow an additional parameter to be passed within the return statement to state why the action was cancelled? Similar to how the actual events do it.

**Comment by thelindat** [comment] 2022-11-05 21:37
To use as a notification message or what?

**Comment by Ehbw2** [comment] 2022-11-05 21:38
> To use as a notification message or what?

yes, I should of probably mentioned that.

**Comment by thelindat** [comment] 2022-11-05 21:42
Seems unnecessary, they can just trigger lib.notify (or favourite notification resource) themselves 🤷

**Comment by Ehbw2** [comment] 2022-11-05 21:47
> Seems unnecessary, they can just trigger lib.notify (or favourite notification resource) themselves 🤷

Good point, only mentioned it since its likely lazy (or incapable) resource developers probably wouldn't trigger notifications themselves. But then thinking about it from that perspective, its unlikely they would pass a reason in the first place.

**Comment by thelindat** [comment] 2022-11-05 22:00
They probably wouldn't even use the hooks.

**Comment by Ehbw2** [comment] 2022-11-05 22:01
Yeah, fair point. Why bother using the API provided for the resource, when you can directly modify the resource and require your "customers" to do the same.

**Comment by thelindat** [comment] 2022-11-06 19:11
Use case?

**Comment by Ehbw2** [comment] 2022-11-06 19:39
> To prevent players from dropping or giving items that have the POL serial for an example.

Wouldn't the swapitems hook already handle that.

**Closed** 2022-11-07 04:05 UTC
Labels: enhancement
