### ISSUE TITLE
Disappearing items and strange weight count

### ISSUE THREAD

**Issue by thejoaoguedes** [overextended/ox_inventory#1380] opened 2023-06-27 00:58 UTC
**Describe the bug**
I noticed that using the latest commits (after release v2.30.7), there are some bugs, like: Items disappearing in stashs and containers, the container has the right weight (as if the item was there, but it isn't), has been reported as well , rollbacks in inventories, for example, when restarting the server (inventories duly saved with /saveinv and with txAdmin's eventHandler, 15 seconds before the server restarts and when restarting). I will attach some information reported by players.

**Framework**
QBCore (v1.2.6)

**Resource version**
Commit: d0e318b9

**To Reproduce**
Honestly, I don't know how exactly, but I'll attach proof of player reports.

**Expected behavior**
The stashes and containers will save correctly, and the weight will be counted inside the containers correctly.

**Videos**
Before restart:
https://www.twitch.tv/videos/1856237982?t=2h43m41s

After restart:
https://medal.tv/games/gta-v/clips/1ggjcgwHfyfJYq/dD6Ilt3YhY1b?invite=cr-MSx5Zk0sMTM1NDM2OTY3LA

**Additional context**
![image](https://github.com/overextended/ox_inventory/assets/80121559/82963b3f-1aaf-4803-bac2-c064784458d4)

**Comment by thelindat** [comment] 2023-06-27 01:19
People have been reporting missing item in stashes for months, with recent reports claiming it started after a release version where saving hadn't been touched for a long time. Last few releases have been an attempt to resolve it but nothing has been reproducible for me - outside of a very unlikely and seemingly unrelated/coincidental issue that required me to remove checks and add a huge delay to simulate a slow save.

**Comment by thejoaoguedes** [comment] 2023-06-27 02:10
I understand, the reason for my report itself is that: using up to v2.30.7, and taking an average of 140 players, I had no reports of these situations that I presented, only using the last commits, anyway, I hope I helped. Thank you for your work for the community!

**Comment by lexinor** [comment] 2023-06-28 13:55
> People have been reporting missing item in stashes for months, with recent reports claiming it started after a release version where saving hadn't been touched for a long time. Last few releases have been an attempt to resolve it but nothing has been reproducible for me - outside of a very unlikely and seemingly unrelated/coincidental issue that required me to remove checks and add a huge delay to simulate a slow save.

Hi, my players are noticing some similar behaviors as mentionned by OP, and after your answer I've got a small question do you think it's a good thing to provoke *saveinv** command when a Player disconnects or just simply reducing the 5min delay for inventories sync ?

Thanks in advance

**Comment by thelindat** [comment] 2023-06-29 00:51
> provoke saveinv command when a Player disconnect

Why?

> reducing the 5min delay for inventories sync

Also why?


The issue is items magically vanishing during a save, and increasing the rate of saves won't affect that.
The reason people are reporting it more than before is because saving was moved from 10m to 5m. The time to remove loaded inventories was also reduced by ~20m.

Every inventory slot is iterated over and added to the save data which is why I don't understand how these stashes are being affected - and never will, because 1 person can't achieve the same results as dozens of people.

**Comment by lexinor** [comment] 2023-06-29 07:02
> > provoke saveinv command when a Player disconnect
> 
> Why?
> 
> > reducing the 5min delay for inventories sync
> 
> Also why?
> 
> The issue is items magically vanishing during a save, and increasing the rate of saves won't affect that. The reason people are reporting it more than before is because saving was moved from 10m to 5m. The time to remove loaded inventories was also reduced by ~20m.
> 
> Every inventory slot is iterated over and added to the save data which is why I don't understand how these stashes are being affected - and never will, because 1 person can't achieve the same results as dozens of people.
> 
> The reported issue is _some_ items vanish, and not that the inventory doesn't save which makes zero sense to me.
> 
> https://github.com/overextended/ox_inventory/blob/a31894729f1d4cb82471ce40538c818f7a7ab8f4/modules/inventory/server.lua#L2197-L2273

Ah, well my bad I guess I missread what was the exact issue. I'm having a lot of issues with duplications in my server where people are taking stuff from stashes / inventories and after a few hours the items are back in the stashes but that might be another issue

**Comment by thelindat** [comment] 2023-07-06 03:36
Possibly resolved with https://github.com/overextended/oxmysql/releases/tag/v2.7.2?

**Closed** 2024-11-09 14:44 UTC
Labels: bug
